# Generated by Django 3.2 on 2023-08-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkshop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('comp_address', models.CharField(max_length=200)),
                ('comp_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category_image', models.ImageField(upload_to='categories')),
                ('price', models.IntegerField()),
                ('product_description', models.TextField()),
                ('image', models.ImageField(upload_to='product')),
                ('owner_details_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vkshop_app.owner_details')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
