# Generated by Django 3.2 on 2023-08-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkshop_app', '0003_auto_20230818_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='owner_details_id',
        ),
    ]
